cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_details, name='cart_details'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove')
]

main/urls.py
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('shop/', views.get_products_list, name='shop'),
    path('shop/<slug:slug>/', views.product_details,  name='product_details'),
    path('shop/category/<slug:category_slug>/', views.get_products_list, name='get_products_list'),
    #path('404/', views.test_404_view, name='test-404'),

]

takizawa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='orders')),
    path('payment/', include('payments.urls', namespace='payments'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

main/models.py
from django.db import models
from django.urls import reverse

from cloudinary.models import CloudinaryField

class Category(models.Model):
    name = models.CharField(max_length=20, unique=True)
    slug = models.SlugField(max_length=20, unique=True)

    class Meta:
        ordering = ['name']
        indexes = [models.Index(fields=['name'])]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('main:get_products_list', args=[self.slug])

    def __str__(self):
        return self.name
    
class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.PROTECT)
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=50, unique=True)
    image = CloudinaryField('image')
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    avaliable = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    discount = models.DecimalField(default=0.00, max_digits=4, decimal_places=2)

    class Meta:
        ordering = ['name']
        indexes = [models.Index(fields = ['id', 'slug']),
                   models.Index(fields = ['name']),
                   models.Index(fields = ['-created'])
                   ]

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('main:product_details', args=[self.slug])
    
    def sell_price(self):
        if self.discount:
            return round(self.price - ((self.price * self.discount) / 100), 2)
        
        return self.price

class ProductImage(models.Model):
    product = models.ForeignKey(Product, related_name='images', on_delete=models.CASCADE)

    image = CloudinaryField('image')

    def __str__(self):
        return f'{self.product.name} - {self.image}'

main/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.template.loader import render_to_string
from django.core.paginator import Paginator
from .models import Product, Category
from cart.forms import CartAddProductForm

def index(request):
    return render(request, 'main/index/index.html')

def get_products_list(request, category_slug = None):
    page = request.GET.get('page', 1)
    category = None
    categories = Category.objects.all().order_by('id')
    products = Product.objects.filter(avaliable=True).order_by('category_id')

    if category_slug:
        category = get_object_or_404(Category, slug = category_slug)
        products = Product.objects.filter(category=category)
        paginator = Paginator(products, 8)
        current_page = paginator.page(int(page))
    else:
        paginator = Paginator(products, 8)
        current_page = paginator.page(int(page))

    if request.htmx:
        html = render_to_string("partials/product/products_list.html", 
                                {'category': category, 
                                 'categories': categories, 
                                 'current_page': current_page, 
                                 'slug_url' : category_slug}, 
                                 request)
        
        return HttpResponse(html)

    return render(request, 'main/product/list.html', {'category': category, 'categories': categories, 'current_page': current_page, 'slug_url' : category_slug})

# def categories_list(request):
#     categories = Category.objects.all().order_by('id')


def product_details(request, slug):
    product = get_object_or_404(Product, slug=slug, avaliable=True)
    cart_product_form = CartAddProductForm
    return render(request, 'main/product/details.html', {'product': product, 'cart_product_form' : cart_product_form})


# def test_404_view(request):
#     return render(request, '404.html', status=404)

main/templates/main/product/details.html
{% extends 'main/base.html' %}
{% load static %}
{% block title%}Takizawa{% endblock %}

{% block content %}
    <div class="detail-product d-flex">
        <div class="product-pic-container">
            <div class="img-wrapper">
                {% if product.images.all %}
                    {% for image in product.images.all %}
                        <img class="product-img" src="{{ image.image.url }}" style="display: none;" data-index="{{ forloop.counter0 }}">
                    {% endfor %}
                {% else %}
                    <img src="{% static "img/noimage.png" %}" class="product-img">
                {% endif %}
                <div class="left-click-zone"></div>
                <div class="right-click-zone"></div>
            </div>
        </div>
        <script>
            const images = document.querySelectorAll('.product-img');
            const leftZone = document.querySelector('.left-click-zone');
            const rightZone = document.querySelector('.right-click-zone');
            let currentIndex = 0;
        
            images[currentIndex].style.display = 'block';
        
            if (images.length > 1) {
                leftZone.addEventListener('click', () => {
                    images[currentIndex].style.display = 'none';
                    currentIndex = (currentIndex - 1 + images.length) % images.length;
                    images[currentIndex].style.display = 'block';
                });
        
                rightZone.addEventListener('click', () => {
                    images[currentIndex].style.display = 'none';
                    currentIndex = (currentIndex + 1) % images.length;
                    images[currentIndex].style.display = 'block';
                });
            } else {
                leftZone.style.display = 'none';
                rightZone.style.display = 'none';
            }
        </script>
        <div class="product-description">
            <h1>{{product.name}}</h1>
            <h2 class="pt-3">Description:</h2>
            <p class="description-text">{{product.description}}<p>
            {% if product.discount %}
                <h2 class="pt-3">{{product.sell_price}}₴</h2>
            {% else %}
                <h2 class="pt-2">{{product.price}}₴</h2>
            {% endif %}

            <form action="{% url "cart:cart_add" product.id %}" class="qform" method="post">
                <div class="cart-form">
                    {{cart_product_form}}
                    {% csrf_token %}
                </div>
                <input type="submit" value="Add to cart" class="cart-btn btn">
            </form>
        </div>
    </div>
{% endblock%}