cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_details, name='cart_details'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove')
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('city-autocomplete/', views.city_autocomplete, name='city-autocomplete'),
    path('address-autocomplete/', views.address_autocomplete, name='address-autocomplete'),
]

takizawa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='orders')),
    path('payment/', include('payments.urls', namespace='payments'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

orders/models.py
from django.db import models
from main.models import Product
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.
class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    phone_number = PhoneNumberField(region='UA',verbose_name="Phone Number")
    city = models.CharField(max_length=100)
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['-created']) 
            ]
        
    def __str__(self):
        return f'Order {self.id}'
    
    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())
    
class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)
    size = models.CharField(max_length=2)

    def __str__(self):
        return str(self.id)
    
    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django import forms
from .models import Order

class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'phone_number', 'city', 'address', 'postal_code']

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None) 
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        if not self.instance.pk:  
            return super().save(commit)
        return self.instance

orders/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from cart.cart import Cart
from .forms import OrderCreateForm 
from .models import OrderItem
import requests
from django.http import HttpResponse
from django.template.loader import render_to_string
from takizawa.settings import NOVA_POST_API_KEY

def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST, request=request)
        if form.is_valid():
            order = form.cleaned_data

            request.session['order'] = {
                'first_name': str(order['first_name']),
                'last_name': str(order['last_name']),
                'email': str(order['email']),
                'phone_number': str(order['phone_number']),
                'address': str(order['address']),
                'postal_code': str(order['postal_code']),
                'city': str(order['city'])
            }

            # print(request.session['order'])
            request.session.modified = True
            return redirect(reverse('payments:process'))
        else:
            return render(request, 'order/create.html', {'cart' : cart, 'form' : form})

    else:
        form = OrderCreateForm(request=request)
        return render(request, 'order/create.html', {'cart' : cart, 'form' : form})
    
def city_autocomplete(request):
    query = request.GET.get('city')
    
    nova_post_api_url = "https://api.novaposhta.ua/v2.0/json/"

    if not query:
        return HttpResponse('')

    body = {
        "apiKey": NOVA_POST_API_KEY,
        "modelName": "AddressGeneral",
        "calledMethod": "searchSettlements",
        "methodProperties": {
            "CityName": query,
            "Limit": 5,
            "Page": 1
        }
    }

    response = requests.post(nova_post_api_url, json=body)

    cities = response.json().get('data', [])[0].get('Addresses', [])

    context = {'cities' : cities}

    html = render_to_string('partials/order/city_suggestions.html', context)

    return HttpResponse(html)

def address_autocomplete(request):
    query = request.GET.get('address')
    city_ref = request.GET.get('city_ref')

    if not query or not city_ref:
        return HttpResponse('')

    url = "https://api.novaposhta.ua/v2.0/json/"
    body = {
        "apiKey": NOVA_POST_API_KEY,
        "modelName": "AddressGeneral",
        "calledMethod": "searchSettlementStreets",
        "methodProperties": {
            "StreetName": query,
            "SettlementRef": city_ref,
            "Limit": 5
        }
    }

    response = requests.post(url, json=body)

    addresses = response.json().get('data', [])[0].get('Addresses', [])

    html = render_to_string('partials/order/address_suggestions.html', {'addresses': addresses})
    return HttpResponse(html)

orders/templates/order/create.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Takizawa{% endblock %}

{% block content %} 
    <div class='order-container'>
        <form action='' method='post' class='order-form d-flex'>
            <div class='order-input-container' style="font-family: 'GalliardStd'">
                <div class='order-input-div'>
                    <label for='id_first_name' class='order-form-label'></label>
                    <input type='text' class='order-input-field form-control form-styleprofile' id='id_first_name' 
                    name='first_name' placeholder='Your First Name' value="{{form.first_name.value|default:'' }}" required>
                </div>
                <div class='order-input-div'>
                    <label for='id_last_name' class='order-form-label'></label>
                    <input type='text' class='order-input-field form-control form-styleprofile' id='id_last_name' 
                    name='last_name' placeholder='Your Last Name' value="{{form.last_name.value|default:'' }}" required>
                </div>
                <div class='order-input-div'>
                    <label for='id_email' class="order-form-label"></label>
                    <input type='text' class='order-input-field form-control form-styleprofile' 
                    id='id_email' 
                    name='email' 
                    placeholder="Your Email" 
                    value="{{form.email.value|default:'' }}" required>
                    {% if form.email.errors %}
                        <div class='input-error-container invalid-feedback'>
                            <p style="color: #FF0000;"> {{form.email.errors.0}} </p>
                        </div>
                    {% endif%}
                </div>
                <div class='order-input-div'>
                    <label for='id_phone_number' class="order-form-label"></label>
                    <input type='text' class='order-input-field form-control form-styleprofile' 
                    id='id_phone_number' 
                    name='phone_number' 
                    placeholder="Your Phone Number"
                    value="{{form.phone_number.value|default:'' }}" required>
                    {% if form.phone_number.errors %}
                        <div class='input-error-container invalid-feedback'>
                            <p style="color: #FF0000;"> {{form.phone_number.errors.0}} </p>
                        </div>
                    {% endif %}
                </div>
                <div class='order-input-div'>
                    <label for='id_city' class='order-form-label'></label>
                    <input 
                        type='text' 
                        class='order-input-field form-control form-styleprofile' 
                        id='id_city' 
                        name='city' 
                        placeholder='Your City'
                        value="{{form.city.value|default:'' }}" 
                        autocomplete="off"
                        hx-get="{% url 'orders:city-autocomplete' %}"
                        hx-trigger="keyup changed delay:300ms"
                        hx-target="#city-suggestions"
                        hx-swap="innerHTML" 
                        required>
                    
                    <input type="hidden" id="id_city_ref" name="city_ref">
                    
                    <div id="city-suggestions"></div>
                </div>
                <div class='order-input-div'>
                    <label for='id_address' class='order-form-label'></label>
                    <input type='text' 
                           class='order-input-field form-control form-styleprofile' 
                           id='id_address' 
                           name='address' 
                           placeholder='Your Address' 
                           value="{{form.address.value|default:'' }}" 

                           hx-get="{% url 'orders:address-autocomplete' %}"
                           hx-trigger="keyup changed delay:300ms"
                           hx-target="#address-suggestions"
                           hx-swap="innerHTML"
                           hx-include="#id_city_ref"
                           autocomplete="off"
                           required>

                    <div id="address-suggestions"></div>
                </div>
                <div class='order-input-div'>
                    <label for='id_postal_code' class='order-form-label'></label>
                    <input type='text' class='order-input-field form-control form-styleprofile' id='id_postal_code' 
                    name='postal_code' placeholder='Your Postal Code' value="{{form.postal_code.value|default:'' }}" required>
                </div>
            </div>
            <div class='order-checkout-container'>
                <h1>Checkout</h1>
                {% for item in cart %}
                    <li class='order-checkout-li' style="font-family: 'GalliardStd'" >{{item.quantity}}x {{item.product.name}}
                        <p>{{item.total_price}}₴</p>
                    </li>   
                {% endfor %}
                <h2>Total: <span style="font-family: 'GalliardStd'; font-size:0.8em;">{{ cart.total_price }}₴</span></h2>
                <p><input type='submit' class='submit-checkout-btn' value='Go to payment'></p>
                {% csrf_token %}
            </div>
        </form>
    </div>
    <script>
        function selectCity(name, ref) {
            document.getElementById("id_city").value = name;
            document.getElementById("id_city_ref").value = ref;
            document.getElementById("city-suggestions").innerHTML = '';
        }
        function selectAddress(name) {
            document.getElementById("id_address").value = name;
            document.getElementById("address-suggestions").innerHTML = '';
        }
    </script>
{% endblock %}

orders/templates/order/created.html
{% extends 'main/base.html' %}

{% block title %}Takizawa{% endblock %}

{% block content %} 
    <h1>Your order was created!</h1>
{% endblock %}